package sample.model;

import java.io.Serializable;

/**
 * <pre>
 * Table        : customers
 * </pre>
 *
 * @mbg.generated 2019-02-27 17:48:22
 */
public class Customers implements Serializable {
    /**
     * <pre>
     * Table        : customers
     * Column       : CustomerId
     * Type         : INTEGER (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private Integer customerid;

    /**
     * <pre>
     * Table        : customers
     * Column       : FirstName
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String firstname;

    /**
     * <pre>
     * Table        : customers
     * Column       : LastName
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String lastname;

    /**
     * <pre>
     * Table        : customers
     * Column       : Company
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String company;

    /**
     * <pre>
     * Table        : customers
     * Column       : Address
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String address;

    /**
     * <pre>
     * Table        : customers
     * Column       : City
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String city;

    /**
     * <pre>
     * Table        : customers
     * Column       : State
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String state;

    /**
     * <pre>
     * Table        : customers
     * Column       : Country
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String country;

    /**
     * <pre>
     * Table        : customers
     * Column       : PostalCode
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String postalcode;

    /**
     * <pre>
     * Table        : customers
     * Column       : Phone
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String phone;

    /**
     * <pre>
     * Table        : customers
     * Column       : Fax
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String fax;

    /**
     * <pre>
     * Table        : customers
     * Column       : Email
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String email;

    /**
     * <pre>
     * Table        : customers
     * Column       : SupportRepId
     * Type         : INTEGER (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private Integer supportrepid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customers
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.CustomerId
     *
     * @return the value of customers.CustomerId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.CustomerId
     *
     * @param customerid the value for customers.CustomerId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.FirstName
     *
     * @return the value of customers.FirstName
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.FirstName
     *
     * @param firstname the value for customers.FirstName
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname == null ? null : firstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.LastName
     *
     * @return the value of customers.LastName
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.LastName
     *
     * @param lastname the value for customers.LastName
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setLastname(String lastname) {
        this.lastname = lastname == null ? null : lastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.Company
     *
     * @return the value of customers.Company
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.Company
     *
     * @param company the value for customers.Company
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.Address
     *
     * @return the value of customers.Address
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.Address
     *
     * @param address the value for customers.Address
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.City
     *
     * @return the value of customers.City
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.City
     *
     * @param city the value for customers.City
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.State
     *
     * @return the value of customers.State
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.State
     *
     * @param state the value for customers.State
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.Country
     *
     * @return the value of customers.Country
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.Country
     *
     * @param country the value for customers.Country
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.PostalCode
     *
     * @return the value of customers.PostalCode
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.PostalCode
     *
     * @param postalcode the value for customers.PostalCode
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode == null ? null : postalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.Phone
     *
     * @return the value of customers.Phone
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.Phone
     *
     * @param phone the value for customers.Phone
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.Fax
     *
     * @return the value of customers.Fax
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.Fax
     *
     * @param fax the value for customers.Fax
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.Email
     *
     * @return the value of customers.Email
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.Email
     *
     * @param email the value for customers.Email
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.SupportRepId
     *
     * @return the value of customers.SupportRepId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Integer getSupportrepid() {
        return supportrepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.SupportRepId
     *
     * @param supportrepid the value for customers.SupportRepId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setSupportrepid(Integer supportrepid) {
        this.supportrepid = supportrepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Customers other = (Customers) that;
        return (this.getCustomerid() == null ? other.getCustomerid() == null : this.getCustomerid().equals(other.getCustomerid()))
            && (this.getFirstname() == null ? other.getFirstname() == null : this.getFirstname().equals(other.getFirstname()))
            && (this.getLastname() == null ? other.getLastname() == null : this.getLastname().equals(other.getLastname()))
            && (this.getCompany() == null ? other.getCompany() == null : this.getCompany().equals(other.getCompany()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getCountry() == null ? other.getCountry() == null : this.getCountry().equals(other.getCountry()))
            && (this.getPostalcode() == null ? other.getPostalcode() == null : this.getPostalcode().equals(other.getPostalcode()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getFax() == null ? other.getFax() == null : this.getFax().equals(other.getFax()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getSupportrepid() == null ? other.getSupportrepid() == null : this.getSupportrepid().equals(other.getSupportrepid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCustomerid() == null) ? 0 : getCustomerid().hashCode());
        result = prime * result + ((getFirstname() == null) ? 0 : getFirstname().hashCode());
        result = prime * result + ((getLastname() == null) ? 0 : getLastname().hashCode());
        result = prime * result + ((getCompany() == null) ? 0 : getCompany().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getCountry() == null) ? 0 : getCountry().hashCode());
        result = prime * result + ((getPostalcode() == null) ? 0 : getPostalcode().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getFax() == null) ? 0 : getFax().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getSupportrepid() == null) ? 0 : getSupportrepid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", customerid=").append(customerid);
        sb.append(", firstname=").append(firstname);
        sb.append(", lastname=").append(lastname);
        sb.append(", company=").append(company);
        sb.append(", address=").append(address);
        sb.append(", city=").append(city);
        sb.append(", state=").append(state);
        sb.append(", country=").append(country);
        sb.append(", postalcode=").append(postalcode);
        sb.append(", phone=").append(phone);
        sb.append(", fax=").append(fax);
        sb.append(", email=").append(email);
        sb.append(", supportrepid=").append(supportrepid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}