package sample.model;

import java.io.Serializable;

/**
 * <pre>
 * Table        : employees
 * </pre>
 *
 * @mbg.generated 2019-02-27 17:48:22
 */
public class Employees implements Serializable {
    /**
     * <pre>
     * Table        : employees
     * Column       : EmployeeId
     * Type         : INTEGER (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private Integer employeeid;

    /**
     * <pre>
     * Table        : employees
     * Column       : LastName
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String lastname;

    /**
     * <pre>
     * Table        : employees
     * Column       : FirstName
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String firstname;

    /**
     * <pre>
     * Table        : employees
     * Column       : Title
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String title;

    /**
     * <pre>
     * Table        : employees
     * Column       : ReportsTo
     * Type         : INTEGER (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private Integer reportsto;

    /**
     * <pre>
     * Table        : employees
     * Column       : BirthDate
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String birthdate;

    /**
     * <pre>
     * Table        : employees
     * Column       : HireDate
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String hiredate;

    /**
     * <pre>
     * Table        : employees
     * Column       : Address
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String address;

    /**
     * <pre>
     * Table        : employees
     * Column       : City
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String city;

    /**
     * <pre>
     * Table        : employees
     * Column       : State
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String state;

    /**
     * <pre>
     * Table        : employees
     * Column       : Country
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String country;

    /**
     * <pre>
     * Table        : employees
     * Column       : PostalCode
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String postalcode;

    /**
     * <pre>
     * Table        : employees
     * Column       : Phone
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String phone;

    /**
     * <pre>
     * Table        : employees
     * Column       : Fax
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String fax;

    /**
     * <pre>
     * Table        : employees
     * Column       : Email
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employees
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.EmployeeId
     *
     * @return the value of employees.EmployeeId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Integer getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.EmployeeId
     *
     * @param employeeid the value for employees.EmployeeId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.LastName
     *
     * @return the value of employees.LastName
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.LastName
     *
     * @param lastname the value for employees.LastName
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setLastname(String lastname) {
        this.lastname = lastname == null ? null : lastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.FirstName
     *
     * @return the value of employees.FirstName
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.FirstName
     *
     * @param firstname the value for employees.FirstName
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname == null ? null : firstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.Title
     *
     * @return the value of employees.Title
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.Title
     *
     * @param title the value for employees.Title
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.ReportsTo
     *
     * @return the value of employees.ReportsTo
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Integer getReportsto() {
        return reportsto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.ReportsTo
     *
     * @param reportsto the value for employees.ReportsTo
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setReportsto(Integer reportsto) {
        this.reportsto = reportsto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.BirthDate
     *
     * @return the value of employees.BirthDate
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.BirthDate
     *
     * @param birthdate the value for employees.BirthDate
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate == null ? null : birthdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.HireDate
     *
     * @return the value of employees.HireDate
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getHiredate() {
        return hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.HireDate
     *
     * @param hiredate the value for employees.HireDate
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setHiredate(String hiredate) {
        this.hiredate = hiredate == null ? null : hiredate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.Address
     *
     * @return the value of employees.Address
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.Address
     *
     * @param address the value for employees.Address
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.City
     *
     * @return the value of employees.City
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.City
     *
     * @param city the value for employees.City
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.State
     *
     * @return the value of employees.State
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.State
     *
     * @param state the value for employees.State
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.Country
     *
     * @return the value of employees.Country
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.Country
     *
     * @param country the value for employees.Country
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.PostalCode
     *
     * @return the value of employees.PostalCode
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.PostalCode
     *
     * @param postalcode the value for employees.PostalCode
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode == null ? null : postalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.Phone
     *
     * @return the value of employees.Phone
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.Phone
     *
     * @param phone the value for employees.Phone
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.Fax
     *
     * @return the value of employees.Fax
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.Fax
     *
     * @param fax the value for employees.Fax
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.Email
     *
     * @return the value of employees.Email
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.Email
     *
     * @param email the value for employees.Email
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Employees other = (Employees) that;
        return (this.getEmployeeid() == null ? other.getEmployeeid() == null : this.getEmployeeid().equals(other.getEmployeeid()))
            && (this.getLastname() == null ? other.getLastname() == null : this.getLastname().equals(other.getLastname()))
            && (this.getFirstname() == null ? other.getFirstname() == null : this.getFirstname().equals(other.getFirstname()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getReportsto() == null ? other.getReportsto() == null : this.getReportsto().equals(other.getReportsto()))
            && (this.getBirthdate() == null ? other.getBirthdate() == null : this.getBirthdate().equals(other.getBirthdate()))
            && (this.getHiredate() == null ? other.getHiredate() == null : this.getHiredate().equals(other.getHiredate()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getCountry() == null ? other.getCountry() == null : this.getCountry().equals(other.getCountry()))
            && (this.getPostalcode() == null ? other.getPostalcode() == null : this.getPostalcode().equals(other.getPostalcode()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getFax() == null ? other.getFax() == null : this.getFax().equals(other.getFax()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEmployeeid() == null) ? 0 : getEmployeeid().hashCode());
        result = prime * result + ((getLastname() == null) ? 0 : getLastname().hashCode());
        result = prime * result + ((getFirstname() == null) ? 0 : getFirstname().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getReportsto() == null) ? 0 : getReportsto().hashCode());
        result = prime * result + ((getBirthdate() == null) ? 0 : getBirthdate().hashCode());
        result = prime * result + ((getHiredate() == null) ? 0 : getHiredate().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getCountry() == null) ? 0 : getCountry().hashCode());
        result = prime * result + ((getPostalcode() == null) ? 0 : getPostalcode().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getFax() == null) ? 0 : getFax().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", employeeid=").append(employeeid);
        sb.append(", lastname=").append(lastname);
        sb.append(", firstname=").append(firstname);
        sb.append(", title=").append(title);
        sb.append(", reportsto=").append(reportsto);
        sb.append(", birthdate=").append(birthdate);
        sb.append(", hiredate=").append(hiredate);
        sb.append(", address=").append(address);
        sb.append(", city=").append(city);
        sb.append(", state=").append(state);
        sb.append(", country=").append(country);
        sb.append(", postalcode=").append(postalcode);
        sb.append(", phone=").append(phone);
        sb.append(", fax=").append(fax);
        sb.append(", email=").append(email);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}