package sample.model;

import java.io.Serializable;

/**
 * <pre>
 * Table        : invoice_items
 * </pre>
 *
 * @mbg.generated 2019-02-27 17:48:22
 */
public class InvoiceItems implements Serializable {
    /**
     * <pre>
     * Table        : invoice_items
     * Column       : InvoiceLineId
     * Type         : INTEGER (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private Integer invoicelineid;

    /**
     * <pre>
     * Table        : invoice_items
     * Column       : InvoiceId
     * Type         : INTEGER (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private Integer invoiceid;

    /**
     * <pre>
     * Table        : invoice_items
     * Column       : TrackId
     * Type         : INTEGER (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private Integer trackid;

    /**
     * <pre>
     * Table        : invoice_items
     * Column       : UnitPrice
     * Type         : FLOAT (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private Double unitprice;

    /**
     * <pre>
     * Table        : invoice_items
     * Column       : Quantity
     * Type         : INTEGER (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice_items.InvoiceLineId
     *
     * @return the value of invoice_items.InvoiceLineId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Integer getInvoicelineid() {
        return invoicelineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice_items.InvoiceLineId
     *
     * @param invoicelineid the value for invoice_items.InvoiceLineId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setInvoicelineid(Integer invoicelineid) {
        this.invoicelineid = invoicelineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice_items.InvoiceId
     *
     * @return the value of invoice_items.InvoiceId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Integer getInvoiceid() {
        return invoiceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice_items.InvoiceId
     *
     * @param invoiceid the value for invoice_items.InvoiceId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setInvoiceid(Integer invoiceid) {
        this.invoiceid = invoiceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice_items.TrackId
     *
     * @return the value of invoice_items.TrackId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Integer getTrackid() {
        return trackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice_items.TrackId
     *
     * @param trackid the value for invoice_items.TrackId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setTrackid(Integer trackid) {
        this.trackid = trackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice_items.UnitPrice
     *
     * @return the value of invoice_items.UnitPrice
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Double getUnitprice() {
        return unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice_items.UnitPrice
     *
     * @param unitprice the value for invoice_items.UnitPrice
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setUnitprice(Double unitprice) {
        this.unitprice = unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice_items.Quantity
     *
     * @return the value of invoice_items.Quantity
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice_items.Quantity
     *
     * @param quantity the value for invoice_items.Quantity
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        InvoiceItems other = (InvoiceItems) that;
        return (this.getInvoicelineid() == null ? other.getInvoicelineid() == null : this.getInvoicelineid().equals(other.getInvoicelineid()))
            && (this.getInvoiceid() == null ? other.getInvoiceid() == null : this.getInvoiceid().equals(other.getInvoiceid()))
            && (this.getTrackid() == null ? other.getTrackid() == null : this.getTrackid().equals(other.getTrackid()))
            && (this.getUnitprice() == null ? other.getUnitprice() == null : this.getUnitprice().equals(other.getUnitprice()))
            && (this.getQuantity() == null ? other.getQuantity() == null : this.getQuantity().equals(other.getQuantity()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getInvoicelineid() == null) ? 0 : getInvoicelineid().hashCode());
        result = prime * result + ((getInvoiceid() == null) ? 0 : getInvoiceid().hashCode());
        result = prime * result + ((getTrackid() == null) ? 0 : getTrackid().hashCode());
        result = prime * result + ((getUnitprice() == null) ? 0 : getUnitprice().hashCode());
        result = prime * result + ((getQuantity() == null) ? 0 : getQuantity().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", invoicelineid=").append(invoicelineid);
        sb.append(", invoiceid=").append(invoiceid);
        sb.append(", trackid=").append(trackid);
        sb.append(", unitprice=").append(unitprice);
        sb.append(", quantity=").append(quantity);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}