package sample.model;

import java.io.Serializable;

/**
 * <pre>
 * Table        : invoices
 * </pre>
 *
 * @mbg.generated 2019-02-27 17:48:22
 */
public class Invoices implements Serializable {
    /**
     * <pre>
     * Table        : invoices
     * Column       : InvoiceId
     * Type         : INTEGER (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private Integer invoiceid;

    /**
     * <pre>
     * Table        : invoices
     * Column       : CustomerId
     * Type         : INTEGER (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private Integer customerid;

    /**
     * <pre>
     * Table        : invoices
     * Column       : InvoiceDate
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String invoicedate;

    /**
     * <pre>
     * Table        : invoices
     * Column       : BillingAddress
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String billingaddress;

    /**
     * <pre>
     * Table        : invoices
     * Column       : BillingCity
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String billingcity;

    /**
     * <pre>
     * Table        : invoices
     * Column       : BillingState
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String billingstate;

    /**
     * <pre>
     * Table        : invoices
     * Column       : BillingCountry
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String billingcountry;

    /**
     * <pre>
     * Table        : invoices
     * Column       : BillingPostalCode
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String billingpostalcode;

    /**
     * <pre>
     * Table        : invoices
     * Column       : Total
     * Type         : FLOAT (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private Double total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoices.InvoiceId
     *
     * @return the value of invoices.InvoiceId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Integer getInvoiceid() {
        return invoiceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoices.InvoiceId
     *
     * @param invoiceid the value for invoices.InvoiceId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setInvoiceid(Integer invoiceid) {
        this.invoiceid = invoiceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoices.CustomerId
     *
     * @return the value of invoices.CustomerId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoices.CustomerId
     *
     * @param customerid the value for invoices.CustomerId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoices.InvoiceDate
     *
     * @return the value of invoices.InvoiceDate
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getInvoicedate() {
        return invoicedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoices.InvoiceDate
     *
     * @param invoicedate the value for invoices.InvoiceDate
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setInvoicedate(String invoicedate) {
        this.invoicedate = invoicedate == null ? null : invoicedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoices.BillingAddress
     *
     * @return the value of invoices.BillingAddress
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getBillingaddress() {
        return billingaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoices.BillingAddress
     *
     * @param billingaddress the value for invoices.BillingAddress
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setBillingaddress(String billingaddress) {
        this.billingaddress = billingaddress == null ? null : billingaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoices.BillingCity
     *
     * @return the value of invoices.BillingCity
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getBillingcity() {
        return billingcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoices.BillingCity
     *
     * @param billingcity the value for invoices.BillingCity
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setBillingcity(String billingcity) {
        this.billingcity = billingcity == null ? null : billingcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoices.BillingState
     *
     * @return the value of invoices.BillingState
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getBillingstate() {
        return billingstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoices.BillingState
     *
     * @param billingstate the value for invoices.BillingState
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setBillingstate(String billingstate) {
        this.billingstate = billingstate == null ? null : billingstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoices.BillingCountry
     *
     * @return the value of invoices.BillingCountry
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getBillingcountry() {
        return billingcountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoices.BillingCountry
     *
     * @param billingcountry the value for invoices.BillingCountry
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setBillingcountry(String billingcountry) {
        this.billingcountry = billingcountry == null ? null : billingcountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoices.BillingPostalCode
     *
     * @return the value of invoices.BillingPostalCode
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getBillingpostalcode() {
        return billingpostalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoices.BillingPostalCode
     *
     * @param billingpostalcode the value for invoices.BillingPostalCode
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setBillingpostalcode(String billingpostalcode) {
        this.billingpostalcode = billingpostalcode == null ? null : billingpostalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoices.Total
     *
     * @return the value of invoices.Total
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Double getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoices.Total
     *
     * @param total the value for invoices.Total
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setTotal(Double total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Invoices other = (Invoices) that;
        return (this.getInvoiceid() == null ? other.getInvoiceid() == null : this.getInvoiceid().equals(other.getInvoiceid()))
            && (this.getCustomerid() == null ? other.getCustomerid() == null : this.getCustomerid().equals(other.getCustomerid()))
            && (this.getInvoicedate() == null ? other.getInvoicedate() == null : this.getInvoicedate().equals(other.getInvoicedate()))
            && (this.getBillingaddress() == null ? other.getBillingaddress() == null : this.getBillingaddress().equals(other.getBillingaddress()))
            && (this.getBillingcity() == null ? other.getBillingcity() == null : this.getBillingcity().equals(other.getBillingcity()))
            && (this.getBillingstate() == null ? other.getBillingstate() == null : this.getBillingstate().equals(other.getBillingstate()))
            && (this.getBillingcountry() == null ? other.getBillingcountry() == null : this.getBillingcountry().equals(other.getBillingcountry()))
            && (this.getBillingpostalcode() == null ? other.getBillingpostalcode() == null : this.getBillingpostalcode().equals(other.getBillingpostalcode()))
            && (this.getTotal() == null ? other.getTotal() == null : this.getTotal().equals(other.getTotal()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getInvoiceid() == null) ? 0 : getInvoiceid().hashCode());
        result = prime * result + ((getCustomerid() == null) ? 0 : getCustomerid().hashCode());
        result = prime * result + ((getInvoicedate() == null) ? 0 : getInvoicedate().hashCode());
        result = prime * result + ((getBillingaddress() == null) ? 0 : getBillingaddress().hashCode());
        result = prime * result + ((getBillingcity() == null) ? 0 : getBillingcity().hashCode());
        result = prime * result + ((getBillingstate() == null) ? 0 : getBillingstate().hashCode());
        result = prime * result + ((getBillingcountry() == null) ? 0 : getBillingcountry().hashCode());
        result = prime * result + ((getBillingpostalcode() == null) ? 0 : getBillingpostalcode().hashCode());
        result = prime * result + ((getTotal() == null) ? 0 : getTotal().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", invoiceid=").append(invoiceid);
        sb.append(", customerid=").append(customerid);
        sb.append(", invoicedate=").append(invoicedate);
        sb.append(", billingaddress=").append(billingaddress);
        sb.append(", billingcity=").append(billingcity);
        sb.append(", billingstate=").append(billingstate);
        sb.append(", billingcountry=").append(billingcountry);
        sb.append(", billingpostalcode=").append(billingpostalcode);
        sb.append(", total=").append(total);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}