package sample.model;

import java.util.ArrayList;
import java.util.List;

public class InvoiceItemsSearchCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public InvoiceItemsSearchCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInvoicelineidIsNull() {
            addCriterion("InvoiceLineId is null");
            return (Criteria) this;
        }

        public Criteria andInvoicelineidIsNotNull() {
            addCriterion("InvoiceLineId is not null");
            return (Criteria) this;
        }

        public Criteria andInvoicelineidEqualTo(Integer value) {
            addCriterion("InvoiceLineId =", value, "invoicelineid");
            return (Criteria) this;
        }

        public Criteria andInvoicelineidNotEqualTo(Integer value) {
            addCriterion("InvoiceLineId <>", value, "invoicelineid");
            return (Criteria) this;
        }

        public Criteria andInvoicelineidGreaterThan(Integer value) {
            addCriterion("InvoiceLineId >", value, "invoicelineid");
            return (Criteria) this;
        }

        public Criteria andInvoicelineidGreaterThanOrEqualTo(Integer value) {
            addCriterion("InvoiceLineId >=", value, "invoicelineid");
            return (Criteria) this;
        }

        public Criteria andInvoicelineidLessThan(Integer value) {
            addCriterion("InvoiceLineId <", value, "invoicelineid");
            return (Criteria) this;
        }

        public Criteria andInvoicelineidLessThanOrEqualTo(Integer value) {
            addCriterion("InvoiceLineId <=", value, "invoicelineid");
            return (Criteria) this;
        }

        public Criteria andInvoicelineidIn(List<Integer> values) {
            addCriterion("InvoiceLineId in", values, "invoicelineid");
            return (Criteria) this;
        }

        public Criteria andInvoicelineidNotIn(List<Integer> values) {
            addCriterion("InvoiceLineId not in", values, "invoicelineid");
            return (Criteria) this;
        }

        public Criteria andInvoicelineidBetween(Integer value1, Integer value2) {
            addCriterion("InvoiceLineId between", value1, value2, "invoicelineid");
            return (Criteria) this;
        }

        public Criteria andInvoicelineidNotBetween(Integer value1, Integer value2) {
            addCriterion("InvoiceLineId not between", value1, value2, "invoicelineid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidIsNull() {
            addCriterion("InvoiceId is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceidIsNotNull() {
            addCriterion("InvoiceId is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceidEqualTo(Integer value) {
            addCriterion("InvoiceId =", value, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidNotEqualTo(Integer value) {
            addCriterion("InvoiceId <>", value, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidGreaterThan(Integer value) {
            addCriterion("InvoiceId >", value, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidGreaterThanOrEqualTo(Integer value) {
            addCriterion("InvoiceId >=", value, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidLessThan(Integer value) {
            addCriterion("InvoiceId <", value, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidLessThanOrEqualTo(Integer value) {
            addCriterion("InvoiceId <=", value, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidIn(List<Integer> values) {
            addCriterion("InvoiceId in", values, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidNotIn(List<Integer> values) {
            addCriterion("InvoiceId not in", values, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidBetween(Integer value1, Integer value2) {
            addCriterion("InvoiceId between", value1, value2, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidNotBetween(Integer value1, Integer value2) {
            addCriterion("InvoiceId not between", value1, value2, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andTrackidIsNull() {
            addCriterion("TrackId is null");
            return (Criteria) this;
        }

        public Criteria andTrackidIsNotNull() {
            addCriterion("TrackId is not null");
            return (Criteria) this;
        }

        public Criteria andTrackidEqualTo(Integer value) {
            addCriterion("TrackId =", value, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidNotEqualTo(Integer value) {
            addCriterion("TrackId <>", value, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidGreaterThan(Integer value) {
            addCriterion("TrackId >", value, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidGreaterThanOrEqualTo(Integer value) {
            addCriterion("TrackId >=", value, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidLessThan(Integer value) {
            addCriterion("TrackId <", value, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidLessThanOrEqualTo(Integer value) {
            addCriterion("TrackId <=", value, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidIn(List<Integer> values) {
            addCriterion("TrackId in", values, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidNotIn(List<Integer> values) {
            addCriterion("TrackId not in", values, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidBetween(Integer value1, Integer value2) {
            addCriterion("TrackId between", value1, value2, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidNotBetween(Integer value1, Integer value2) {
            addCriterion("TrackId not between", value1, value2, "trackid");
            return (Criteria) this;
        }

        public Criteria andUnitpriceIsNull() {
            addCriterion("UnitPrice is null");
            return (Criteria) this;
        }

        public Criteria andUnitpriceIsNotNull() {
            addCriterion("UnitPrice is not null");
            return (Criteria) this;
        }

        public Criteria andUnitpriceEqualTo(Double value) {
            addCriterion("UnitPrice =", value, "unitprice");
            return (Criteria) this;
        }

        public Criteria andUnitpriceNotEqualTo(Double value) {
            addCriterion("UnitPrice <>", value, "unitprice");
            return (Criteria) this;
        }

        public Criteria andUnitpriceGreaterThan(Double value) {
            addCriterion("UnitPrice >", value, "unitprice");
            return (Criteria) this;
        }

        public Criteria andUnitpriceGreaterThanOrEqualTo(Double value) {
            addCriterion("UnitPrice >=", value, "unitprice");
            return (Criteria) this;
        }

        public Criteria andUnitpriceLessThan(Double value) {
            addCriterion("UnitPrice <", value, "unitprice");
            return (Criteria) this;
        }

        public Criteria andUnitpriceLessThanOrEqualTo(Double value) {
            addCriterion("UnitPrice <=", value, "unitprice");
            return (Criteria) this;
        }

        public Criteria andUnitpriceIn(List<Double> values) {
            addCriterion("UnitPrice in", values, "unitprice");
            return (Criteria) this;
        }

        public Criteria andUnitpriceNotIn(List<Double> values) {
            addCriterion("UnitPrice not in", values, "unitprice");
            return (Criteria) this;
        }

        public Criteria andUnitpriceBetween(Double value1, Double value2) {
            addCriterion("UnitPrice between", value1, value2, "unitprice");
            return (Criteria) this;
        }

        public Criteria andUnitpriceNotBetween(Double value1, Double value2) {
            addCriterion("UnitPrice not between", value1, value2, "unitprice");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNull() {
            addCriterion("Quantity is null");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNotNull() {
            addCriterion("Quantity is not null");
            return (Criteria) this;
        }

        public Criteria andQuantityEqualTo(Integer value) {
            addCriterion("Quantity =", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotEqualTo(Integer value) {
            addCriterion("Quantity <>", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThan(Integer value) {
            addCriterion("Quantity >", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("Quantity >=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThan(Integer value) {
            addCriterion("Quantity <", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("Quantity <=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityIn(List<Integer> values) {
            addCriterion("Quantity in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotIn(List<Integer> values) {
            addCriterion("Quantity not in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityBetween(Integer value1, Integer value2) {
            addCriterion("Quantity between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("Quantity not between", value1, value2, "quantity");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table invoice_items
     *
     * @mbg.generated do_not_delete_during_merge 2019-02-27 17:48:22
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}