package sample.model;

import java.util.ArrayList;
import java.util.List;

public class InvoicesSearchCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public InvoicesSearchCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInvoiceidIsNull() {
            addCriterion("InvoiceId is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceidIsNotNull() {
            addCriterion("InvoiceId is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceidEqualTo(Integer value) {
            addCriterion("InvoiceId =", value, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidNotEqualTo(Integer value) {
            addCriterion("InvoiceId <>", value, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidGreaterThan(Integer value) {
            addCriterion("InvoiceId >", value, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidGreaterThanOrEqualTo(Integer value) {
            addCriterion("InvoiceId >=", value, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidLessThan(Integer value) {
            addCriterion("InvoiceId <", value, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidLessThanOrEqualTo(Integer value) {
            addCriterion("InvoiceId <=", value, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidIn(List<Integer> values) {
            addCriterion("InvoiceId in", values, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidNotIn(List<Integer> values) {
            addCriterion("InvoiceId not in", values, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidBetween(Integer value1, Integer value2) {
            addCriterion("InvoiceId between", value1, value2, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidNotBetween(Integer value1, Integer value2) {
            addCriterion("InvoiceId not between", value1, value2, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andCustomeridIsNull() {
            addCriterion("CustomerId is null");
            return (Criteria) this;
        }

        public Criteria andCustomeridIsNotNull() {
            addCriterion("CustomerId is not null");
            return (Criteria) this;
        }

        public Criteria andCustomeridEqualTo(Integer value) {
            addCriterion("CustomerId =", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotEqualTo(Integer value) {
            addCriterion("CustomerId <>", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridGreaterThan(Integer value) {
            addCriterion("CustomerId >", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridGreaterThanOrEqualTo(Integer value) {
            addCriterion("CustomerId >=", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridLessThan(Integer value) {
            addCriterion("CustomerId <", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridLessThanOrEqualTo(Integer value) {
            addCriterion("CustomerId <=", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridIn(List<Integer> values) {
            addCriterion("CustomerId in", values, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotIn(List<Integer> values) {
            addCriterion("CustomerId not in", values, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridBetween(Integer value1, Integer value2) {
            addCriterion("CustomerId between", value1, value2, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotBetween(Integer value1, Integer value2) {
            addCriterion("CustomerId not between", value1, value2, "customerid");
            return (Criteria) this;
        }

        public Criteria andInvoicedateIsNull() {
            addCriterion("InvoiceDate is null");
            return (Criteria) this;
        }

        public Criteria andInvoicedateIsNotNull() {
            addCriterion("InvoiceDate is not null");
            return (Criteria) this;
        }

        public Criteria andInvoicedateEqualTo(String value) {
            addCriterion("InvoiceDate =", value, "invoicedate");
            return (Criteria) this;
        }

        public Criteria andInvoicedateNotEqualTo(String value) {
            addCriterion("InvoiceDate <>", value, "invoicedate");
            return (Criteria) this;
        }

        public Criteria andInvoicedateGreaterThan(String value) {
            addCriterion("InvoiceDate >", value, "invoicedate");
            return (Criteria) this;
        }

        public Criteria andInvoicedateGreaterThanOrEqualTo(String value) {
            addCriterion("InvoiceDate >=", value, "invoicedate");
            return (Criteria) this;
        }

        public Criteria andInvoicedateLessThan(String value) {
            addCriterion("InvoiceDate <", value, "invoicedate");
            return (Criteria) this;
        }

        public Criteria andInvoicedateLessThanOrEqualTo(String value) {
            addCriterion("InvoiceDate <=", value, "invoicedate");
            return (Criteria) this;
        }

        public Criteria andInvoicedateLike(String value) {
            addCriterion("InvoiceDate like", value, "invoicedate");
            return (Criteria) this;
        }

        public Criteria andInvoicedateNotLike(String value) {
            addCriterion("InvoiceDate not like", value, "invoicedate");
            return (Criteria) this;
        }

        public Criteria andInvoicedateIn(List<String> values) {
            addCriterion("InvoiceDate in", values, "invoicedate");
            return (Criteria) this;
        }

        public Criteria andInvoicedateNotIn(List<String> values) {
            addCriterion("InvoiceDate not in", values, "invoicedate");
            return (Criteria) this;
        }

        public Criteria andInvoicedateBetween(String value1, String value2) {
            addCriterion("InvoiceDate between", value1, value2, "invoicedate");
            return (Criteria) this;
        }

        public Criteria andInvoicedateNotBetween(String value1, String value2) {
            addCriterion("InvoiceDate not between", value1, value2, "invoicedate");
            return (Criteria) this;
        }

        public Criteria andBillingaddressIsNull() {
            addCriterion("BillingAddress is null");
            return (Criteria) this;
        }

        public Criteria andBillingaddressIsNotNull() {
            addCriterion("BillingAddress is not null");
            return (Criteria) this;
        }

        public Criteria andBillingaddressEqualTo(String value) {
            addCriterion("BillingAddress =", value, "billingaddress");
            return (Criteria) this;
        }

        public Criteria andBillingaddressNotEqualTo(String value) {
            addCriterion("BillingAddress <>", value, "billingaddress");
            return (Criteria) this;
        }

        public Criteria andBillingaddressGreaterThan(String value) {
            addCriterion("BillingAddress >", value, "billingaddress");
            return (Criteria) this;
        }

        public Criteria andBillingaddressGreaterThanOrEqualTo(String value) {
            addCriterion("BillingAddress >=", value, "billingaddress");
            return (Criteria) this;
        }

        public Criteria andBillingaddressLessThan(String value) {
            addCriterion("BillingAddress <", value, "billingaddress");
            return (Criteria) this;
        }

        public Criteria andBillingaddressLessThanOrEqualTo(String value) {
            addCriterion("BillingAddress <=", value, "billingaddress");
            return (Criteria) this;
        }

        public Criteria andBillingaddressLike(String value) {
            addCriterion("BillingAddress like", value, "billingaddress");
            return (Criteria) this;
        }

        public Criteria andBillingaddressNotLike(String value) {
            addCriterion("BillingAddress not like", value, "billingaddress");
            return (Criteria) this;
        }

        public Criteria andBillingaddressIn(List<String> values) {
            addCriterion("BillingAddress in", values, "billingaddress");
            return (Criteria) this;
        }

        public Criteria andBillingaddressNotIn(List<String> values) {
            addCriterion("BillingAddress not in", values, "billingaddress");
            return (Criteria) this;
        }

        public Criteria andBillingaddressBetween(String value1, String value2) {
            addCriterion("BillingAddress between", value1, value2, "billingaddress");
            return (Criteria) this;
        }

        public Criteria andBillingaddressNotBetween(String value1, String value2) {
            addCriterion("BillingAddress not between", value1, value2, "billingaddress");
            return (Criteria) this;
        }

        public Criteria andBillingcityIsNull() {
            addCriterion("BillingCity is null");
            return (Criteria) this;
        }

        public Criteria andBillingcityIsNotNull() {
            addCriterion("BillingCity is not null");
            return (Criteria) this;
        }

        public Criteria andBillingcityEqualTo(String value) {
            addCriterion("BillingCity =", value, "billingcity");
            return (Criteria) this;
        }

        public Criteria andBillingcityNotEqualTo(String value) {
            addCriterion("BillingCity <>", value, "billingcity");
            return (Criteria) this;
        }

        public Criteria andBillingcityGreaterThan(String value) {
            addCriterion("BillingCity >", value, "billingcity");
            return (Criteria) this;
        }

        public Criteria andBillingcityGreaterThanOrEqualTo(String value) {
            addCriterion("BillingCity >=", value, "billingcity");
            return (Criteria) this;
        }

        public Criteria andBillingcityLessThan(String value) {
            addCriterion("BillingCity <", value, "billingcity");
            return (Criteria) this;
        }

        public Criteria andBillingcityLessThanOrEqualTo(String value) {
            addCriterion("BillingCity <=", value, "billingcity");
            return (Criteria) this;
        }

        public Criteria andBillingcityLike(String value) {
            addCriterion("BillingCity like", value, "billingcity");
            return (Criteria) this;
        }

        public Criteria andBillingcityNotLike(String value) {
            addCriterion("BillingCity not like", value, "billingcity");
            return (Criteria) this;
        }

        public Criteria andBillingcityIn(List<String> values) {
            addCriterion("BillingCity in", values, "billingcity");
            return (Criteria) this;
        }

        public Criteria andBillingcityNotIn(List<String> values) {
            addCriterion("BillingCity not in", values, "billingcity");
            return (Criteria) this;
        }

        public Criteria andBillingcityBetween(String value1, String value2) {
            addCriterion("BillingCity between", value1, value2, "billingcity");
            return (Criteria) this;
        }

        public Criteria andBillingcityNotBetween(String value1, String value2) {
            addCriterion("BillingCity not between", value1, value2, "billingcity");
            return (Criteria) this;
        }

        public Criteria andBillingstateIsNull() {
            addCriterion("BillingState is null");
            return (Criteria) this;
        }

        public Criteria andBillingstateIsNotNull() {
            addCriterion("BillingState is not null");
            return (Criteria) this;
        }

        public Criteria andBillingstateEqualTo(String value) {
            addCriterion("BillingState =", value, "billingstate");
            return (Criteria) this;
        }

        public Criteria andBillingstateNotEqualTo(String value) {
            addCriterion("BillingState <>", value, "billingstate");
            return (Criteria) this;
        }

        public Criteria andBillingstateGreaterThan(String value) {
            addCriterion("BillingState >", value, "billingstate");
            return (Criteria) this;
        }

        public Criteria andBillingstateGreaterThanOrEqualTo(String value) {
            addCriterion("BillingState >=", value, "billingstate");
            return (Criteria) this;
        }

        public Criteria andBillingstateLessThan(String value) {
            addCriterion("BillingState <", value, "billingstate");
            return (Criteria) this;
        }

        public Criteria andBillingstateLessThanOrEqualTo(String value) {
            addCriterion("BillingState <=", value, "billingstate");
            return (Criteria) this;
        }

        public Criteria andBillingstateLike(String value) {
            addCriterion("BillingState like", value, "billingstate");
            return (Criteria) this;
        }

        public Criteria andBillingstateNotLike(String value) {
            addCriterion("BillingState not like", value, "billingstate");
            return (Criteria) this;
        }

        public Criteria andBillingstateIn(List<String> values) {
            addCriterion("BillingState in", values, "billingstate");
            return (Criteria) this;
        }

        public Criteria andBillingstateNotIn(List<String> values) {
            addCriterion("BillingState not in", values, "billingstate");
            return (Criteria) this;
        }

        public Criteria andBillingstateBetween(String value1, String value2) {
            addCriterion("BillingState between", value1, value2, "billingstate");
            return (Criteria) this;
        }

        public Criteria andBillingstateNotBetween(String value1, String value2) {
            addCriterion("BillingState not between", value1, value2, "billingstate");
            return (Criteria) this;
        }

        public Criteria andBillingcountryIsNull() {
            addCriterion("BillingCountry is null");
            return (Criteria) this;
        }

        public Criteria andBillingcountryIsNotNull() {
            addCriterion("BillingCountry is not null");
            return (Criteria) this;
        }

        public Criteria andBillingcountryEqualTo(String value) {
            addCriterion("BillingCountry =", value, "billingcountry");
            return (Criteria) this;
        }

        public Criteria andBillingcountryNotEqualTo(String value) {
            addCriterion("BillingCountry <>", value, "billingcountry");
            return (Criteria) this;
        }

        public Criteria andBillingcountryGreaterThan(String value) {
            addCriterion("BillingCountry >", value, "billingcountry");
            return (Criteria) this;
        }

        public Criteria andBillingcountryGreaterThanOrEqualTo(String value) {
            addCriterion("BillingCountry >=", value, "billingcountry");
            return (Criteria) this;
        }

        public Criteria andBillingcountryLessThan(String value) {
            addCriterion("BillingCountry <", value, "billingcountry");
            return (Criteria) this;
        }

        public Criteria andBillingcountryLessThanOrEqualTo(String value) {
            addCriterion("BillingCountry <=", value, "billingcountry");
            return (Criteria) this;
        }

        public Criteria andBillingcountryLike(String value) {
            addCriterion("BillingCountry like", value, "billingcountry");
            return (Criteria) this;
        }

        public Criteria andBillingcountryNotLike(String value) {
            addCriterion("BillingCountry not like", value, "billingcountry");
            return (Criteria) this;
        }

        public Criteria andBillingcountryIn(List<String> values) {
            addCriterion("BillingCountry in", values, "billingcountry");
            return (Criteria) this;
        }

        public Criteria andBillingcountryNotIn(List<String> values) {
            addCriterion("BillingCountry not in", values, "billingcountry");
            return (Criteria) this;
        }

        public Criteria andBillingcountryBetween(String value1, String value2) {
            addCriterion("BillingCountry between", value1, value2, "billingcountry");
            return (Criteria) this;
        }

        public Criteria andBillingcountryNotBetween(String value1, String value2) {
            addCriterion("BillingCountry not between", value1, value2, "billingcountry");
            return (Criteria) this;
        }

        public Criteria andBillingpostalcodeIsNull() {
            addCriterion("BillingPostalCode is null");
            return (Criteria) this;
        }

        public Criteria andBillingpostalcodeIsNotNull() {
            addCriterion("BillingPostalCode is not null");
            return (Criteria) this;
        }

        public Criteria andBillingpostalcodeEqualTo(String value) {
            addCriterion("BillingPostalCode =", value, "billingpostalcode");
            return (Criteria) this;
        }

        public Criteria andBillingpostalcodeNotEqualTo(String value) {
            addCriterion("BillingPostalCode <>", value, "billingpostalcode");
            return (Criteria) this;
        }

        public Criteria andBillingpostalcodeGreaterThan(String value) {
            addCriterion("BillingPostalCode >", value, "billingpostalcode");
            return (Criteria) this;
        }

        public Criteria andBillingpostalcodeGreaterThanOrEqualTo(String value) {
            addCriterion("BillingPostalCode >=", value, "billingpostalcode");
            return (Criteria) this;
        }

        public Criteria andBillingpostalcodeLessThan(String value) {
            addCriterion("BillingPostalCode <", value, "billingpostalcode");
            return (Criteria) this;
        }

        public Criteria andBillingpostalcodeLessThanOrEqualTo(String value) {
            addCriterion("BillingPostalCode <=", value, "billingpostalcode");
            return (Criteria) this;
        }

        public Criteria andBillingpostalcodeLike(String value) {
            addCriterion("BillingPostalCode like", value, "billingpostalcode");
            return (Criteria) this;
        }

        public Criteria andBillingpostalcodeNotLike(String value) {
            addCriterion("BillingPostalCode not like", value, "billingpostalcode");
            return (Criteria) this;
        }

        public Criteria andBillingpostalcodeIn(List<String> values) {
            addCriterion("BillingPostalCode in", values, "billingpostalcode");
            return (Criteria) this;
        }

        public Criteria andBillingpostalcodeNotIn(List<String> values) {
            addCriterion("BillingPostalCode not in", values, "billingpostalcode");
            return (Criteria) this;
        }

        public Criteria andBillingpostalcodeBetween(String value1, String value2) {
            addCriterion("BillingPostalCode between", value1, value2, "billingpostalcode");
            return (Criteria) this;
        }

        public Criteria andBillingpostalcodeNotBetween(String value1, String value2) {
            addCriterion("BillingPostalCode not between", value1, value2, "billingpostalcode");
            return (Criteria) this;
        }

        public Criteria andTotalIsNull() {
            addCriterion("Total is null");
            return (Criteria) this;
        }

        public Criteria andTotalIsNotNull() {
            addCriterion("Total is not null");
            return (Criteria) this;
        }

        public Criteria andTotalEqualTo(Double value) {
            addCriterion("Total =", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotEqualTo(Double value) {
            addCriterion("Total <>", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalGreaterThan(Double value) {
            addCriterion("Total >", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalGreaterThanOrEqualTo(Double value) {
            addCriterion("Total >=", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLessThan(Double value) {
            addCriterion("Total <", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLessThanOrEqualTo(Double value) {
            addCriterion("Total <=", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalIn(List<Double> values) {
            addCriterion("Total in", values, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotIn(List<Double> values) {
            addCriterion("Total not in", values, "total");
            return (Criteria) this;
        }

        public Criteria andTotalBetween(Double value1, Double value2) {
            addCriterion("Total between", value1, value2, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotBetween(Double value1, Double value2) {
            addCriterion("Total not between", value1, value2, "total");
            return (Criteria) this;
        }

        public Criteria andInvoicedateLikeInsensitive(String value) {
            addCriterion("upper(InvoiceDate) like", value.toUpperCase(), "invoicedate");
            return (Criteria) this;
        }

        public Criteria andBillingaddressLikeInsensitive(String value) {
            addCriterion("upper(BillingAddress) like", value.toUpperCase(), "billingaddress");
            return (Criteria) this;
        }

        public Criteria andBillingcityLikeInsensitive(String value) {
            addCriterion("upper(BillingCity) like", value.toUpperCase(), "billingcity");
            return (Criteria) this;
        }

        public Criteria andBillingstateLikeInsensitive(String value) {
            addCriterion("upper(BillingState) like", value.toUpperCase(), "billingstate");
            return (Criteria) this;
        }

        public Criteria andBillingcountryLikeInsensitive(String value) {
            addCriterion("upper(BillingCountry) like", value.toUpperCase(), "billingcountry");
            return (Criteria) this;
        }

        public Criteria andBillingpostalcodeLikeInsensitive(String value) {
            addCriterion("upper(BillingPostalCode) like", value.toUpperCase(), "billingpostalcode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table invoices
     *
     * @mbg.generated do_not_delete_during_merge 2019-02-27 17:48:22
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}