package sample.model;

import java.io.Serializable;

/**
 * <pre>
 * Table        : media_types
 * </pre>
 *
 * @mbg.generated 2019-02-27 17:48:22
 */
public class MediaTypes implements Serializable {
    /**
     * <pre>
     * Table        : media_types
     * Column       : MediaTypeId
     * Type         : INTEGER (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private Integer mediatypeid;

    /**
     * <pre>
     * Table        : media_types
     * Column       : Name
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table media_types
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_types.MediaTypeId
     *
     * @return the value of media_types.MediaTypeId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Integer getMediatypeid() {
        return mediatypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_types.MediaTypeId
     *
     * @param mediatypeid the value for media_types.MediaTypeId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setMediatypeid(Integer mediatypeid) {
        this.mediatypeid = mediatypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_types.Name
     *
     * @return the value of media_types.Name
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_types.Name
     *
     * @param name the value for media_types.Name
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_types
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MediaTypes other = (MediaTypes) that;
        return (this.getMediatypeid() == null ? other.getMediatypeid() == null : this.getMediatypeid().equals(other.getMediatypeid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_types
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMediatypeid() == null) ? 0 : getMediatypeid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_types
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mediatypeid=").append(mediatypeid);
        sb.append(", name=").append(name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}