package sample.model;

import java.io.Serializable;

/**
 * <pre>
 * Table        : playlists
 * </pre>
 *
 * @mbg.generated 2019-02-27 17:48:22
 */
public class Playlists implements Serializable {
    /**
     * <pre>
     * Table        : playlists
     * Column       : PlaylistId
     * Type         : INTEGER (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private Integer playlistid;

    /**
     * <pre>
     * Table        : playlists
     * Column       : Name
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table playlists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column playlists.PlaylistId
     *
     * @return the value of playlists.PlaylistId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Integer getPlaylistid() {
        return playlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column playlists.PlaylistId
     *
     * @param playlistid the value for playlists.PlaylistId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setPlaylistid(Integer playlistid) {
        this.playlistid = playlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column playlists.Name
     *
     * @return the value of playlists.Name
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column playlists.Name
     *
     * @param name the value for playlists.Name
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Playlists other = (Playlists) that;
        return (this.getPlaylistid() == null ? other.getPlaylistid() == null : this.getPlaylistid().equals(other.getPlaylistid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPlaylistid() == null) ? 0 : getPlaylistid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", playlistid=").append(playlistid);
        sb.append(", name=").append(name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}