package sample.model;

import java.util.ArrayList;
import java.util.List;

public class PlaylistTrackSearchCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public PlaylistTrackSearchCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPlaylistidIsNull() {
            addCriterion("PlaylistId is null");
            return (Criteria) this;
        }

        public Criteria andPlaylistidIsNotNull() {
            addCriterion("PlaylistId is not null");
            return (Criteria) this;
        }

        public Criteria andPlaylistidEqualTo(Integer value) {
            addCriterion("PlaylistId =", value, "playlistid");
            return (Criteria) this;
        }

        public Criteria andPlaylistidNotEqualTo(Integer value) {
            addCriterion("PlaylistId <>", value, "playlistid");
            return (Criteria) this;
        }

        public Criteria andPlaylistidGreaterThan(Integer value) {
            addCriterion("PlaylistId >", value, "playlistid");
            return (Criteria) this;
        }

        public Criteria andPlaylistidGreaterThanOrEqualTo(Integer value) {
            addCriterion("PlaylistId >=", value, "playlistid");
            return (Criteria) this;
        }

        public Criteria andPlaylistidLessThan(Integer value) {
            addCriterion("PlaylistId <", value, "playlistid");
            return (Criteria) this;
        }

        public Criteria andPlaylistidLessThanOrEqualTo(Integer value) {
            addCriterion("PlaylistId <=", value, "playlistid");
            return (Criteria) this;
        }

        public Criteria andPlaylistidIn(List<Integer> values) {
            addCriterion("PlaylistId in", values, "playlistid");
            return (Criteria) this;
        }

        public Criteria andPlaylistidNotIn(List<Integer> values) {
            addCriterion("PlaylistId not in", values, "playlistid");
            return (Criteria) this;
        }

        public Criteria andPlaylistidBetween(Integer value1, Integer value2) {
            addCriterion("PlaylistId between", value1, value2, "playlistid");
            return (Criteria) this;
        }

        public Criteria andPlaylistidNotBetween(Integer value1, Integer value2) {
            addCriterion("PlaylistId not between", value1, value2, "playlistid");
            return (Criteria) this;
        }

        public Criteria andTrackidIsNull() {
            addCriterion("TrackId is null");
            return (Criteria) this;
        }

        public Criteria andTrackidIsNotNull() {
            addCriterion("TrackId is not null");
            return (Criteria) this;
        }

        public Criteria andTrackidEqualTo(Integer value) {
            addCriterion("TrackId =", value, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidNotEqualTo(Integer value) {
            addCriterion("TrackId <>", value, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidGreaterThan(Integer value) {
            addCriterion("TrackId >", value, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidGreaterThanOrEqualTo(Integer value) {
            addCriterion("TrackId >=", value, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidLessThan(Integer value) {
            addCriterion("TrackId <", value, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidLessThanOrEqualTo(Integer value) {
            addCriterion("TrackId <=", value, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidIn(List<Integer> values) {
            addCriterion("TrackId in", values, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidNotIn(List<Integer> values) {
            addCriterion("TrackId not in", values, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidBetween(Integer value1, Integer value2) {
            addCriterion("TrackId between", value1, value2, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidNotBetween(Integer value1, Integer value2) {
            addCriterion("TrackId not between", value1, value2, "trackid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table playlist_track
     *
     * @mbg.generated do_not_delete_during_merge 2019-02-27 17:48:22
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}