package sample.model;

import java.io.Serializable;

/**
 * <pre>
 * Table        : tracks
 * </pre>
 *
 * @mbg.generated 2019-02-27 17:48:22
 */
public class Tracks implements Serializable {
    /**
     * <pre>
     * Table        : tracks
     * Column       : TrackId
     * Type         : INTEGER (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private Integer trackid;

    /**
     * <pre>
     * Table        : tracks
     * Column       : Name
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String name;

    /**
     * <pre>
     * Table        : tracks
     * Column       : AlbumId
     * Type         : INTEGER (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private Integer albumid;

    /**
     * <pre>
     * Table        : tracks
     * Column       : MediaTypeId
     * Type         : INTEGER (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private Integer mediatypeid;

    /**
     * <pre>
     * Table        : tracks
     * Column       : GenreId
     * Type         : INTEGER (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private Integer genreid;

    /**
     * <pre>
     * Table        : tracks
     * Column       : Composer
     * Type         : VARCHAR (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private String composer;

    /**
     * <pre>
     * Table        : tracks
     * Column       : Milliseconds
     * Type         : INTEGER (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private Integer milliseconds;

    /**
     * <pre>
     * Table        : tracks
     * Column       : Bytes
     * Type         : INTEGER (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private Integer bytes;

    /**
     * <pre>
     * Table        : tracks
     * Column       : UnitPrice
     * Type         : FLOAT (2000000000)
     * </pre>
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private Double unitprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tracks
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracks.TrackId
     *
     * @return the value of tracks.TrackId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Integer getTrackid() {
        return trackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracks.TrackId
     *
     * @param trackid the value for tracks.TrackId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setTrackid(Integer trackid) {
        this.trackid = trackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracks.Name
     *
     * @return the value of tracks.Name
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracks.Name
     *
     * @param name the value for tracks.Name
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracks.AlbumId
     *
     * @return the value of tracks.AlbumId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Integer getAlbumid() {
        return albumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracks.AlbumId
     *
     * @param albumid the value for tracks.AlbumId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setAlbumid(Integer albumid) {
        this.albumid = albumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracks.MediaTypeId
     *
     * @return the value of tracks.MediaTypeId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Integer getMediatypeid() {
        return mediatypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracks.MediaTypeId
     *
     * @param mediatypeid the value for tracks.MediaTypeId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setMediatypeid(Integer mediatypeid) {
        this.mediatypeid = mediatypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracks.GenreId
     *
     * @return the value of tracks.GenreId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Integer getGenreid() {
        return genreid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracks.GenreId
     *
     * @param genreid the value for tracks.GenreId
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setGenreid(Integer genreid) {
        this.genreid = genreid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracks.Composer
     *
     * @return the value of tracks.Composer
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public String getComposer() {
        return composer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracks.Composer
     *
     * @param composer the value for tracks.Composer
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setComposer(String composer) {
        this.composer = composer == null ? null : composer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracks.Milliseconds
     *
     * @return the value of tracks.Milliseconds
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Integer getMilliseconds() {
        return milliseconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracks.Milliseconds
     *
     * @param milliseconds the value for tracks.Milliseconds
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setMilliseconds(Integer milliseconds) {
        this.milliseconds = milliseconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracks.Bytes
     *
     * @return the value of tracks.Bytes
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Integer getBytes() {
        return bytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracks.Bytes
     *
     * @param bytes the value for tracks.Bytes
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setBytes(Integer bytes) {
        this.bytes = bytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracks.UnitPrice
     *
     * @return the value of tracks.UnitPrice
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public Double getUnitprice() {
        return unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracks.UnitPrice
     *
     * @param unitprice the value for tracks.UnitPrice
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    public void setUnitprice(Double unitprice) {
        this.unitprice = unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracks
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Tracks other = (Tracks) that;
        return (this.getTrackid() == null ? other.getTrackid() == null : this.getTrackid().equals(other.getTrackid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getAlbumid() == null ? other.getAlbumid() == null : this.getAlbumid().equals(other.getAlbumid()))
            && (this.getMediatypeid() == null ? other.getMediatypeid() == null : this.getMediatypeid().equals(other.getMediatypeid()))
            && (this.getGenreid() == null ? other.getGenreid() == null : this.getGenreid().equals(other.getGenreid()))
            && (this.getComposer() == null ? other.getComposer() == null : this.getComposer().equals(other.getComposer()))
            && (this.getMilliseconds() == null ? other.getMilliseconds() == null : this.getMilliseconds().equals(other.getMilliseconds()))
            && (this.getBytes() == null ? other.getBytes() == null : this.getBytes().equals(other.getBytes()))
            && (this.getUnitprice() == null ? other.getUnitprice() == null : this.getUnitprice().equals(other.getUnitprice()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracks
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTrackid() == null) ? 0 : getTrackid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getAlbumid() == null) ? 0 : getAlbumid().hashCode());
        result = prime * result + ((getMediatypeid() == null) ? 0 : getMediatypeid().hashCode());
        result = prime * result + ((getGenreid() == null) ? 0 : getGenreid().hashCode());
        result = prime * result + ((getComposer() == null) ? 0 : getComposer().hashCode());
        result = prime * result + ((getMilliseconds() == null) ? 0 : getMilliseconds().hashCode());
        result = prime * result + ((getBytes() == null) ? 0 : getBytes().hashCode());
        result = prime * result + ((getUnitprice() == null) ? 0 : getUnitprice().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracks
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", trackid=").append(trackid);
        sb.append(", name=").append(name);
        sb.append(", albumid=").append(albumid);
        sb.append(", mediatypeid=").append(mediatypeid);
        sb.append(", genreid=").append(genreid);
        sb.append(", composer=").append(composer);
        sb.append(", milliseconds=").append(milliseconds);
        sb.append(", bytes=").append(bytes);
        sb.append(", unitprice=").append(unitprice);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}