package sample.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import sample.model.Artists;
import sample.model.ArtistsSearchCriteria;

@Mapper
public interface ArtistsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    long countBySearchCriteria(ArtistsSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int deleteBySearchCriteria(ArtistsSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int deleteByPrimaryKey(Integer artistid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int insert(Artists record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int insertSelective(Artists record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    List<Artists> selectBySearchCriteriaWithRowbounds(ArtistsSearchCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    List<Artists> selectBySearchCriteria(ArtistsSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    Artists selectByPrimaryKey(Integer artistid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateBySearchCriteriaSelective(@Param("record") Artists record, @Param("example") ArtistsSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateBySearchCriteria(@Param("record") Artists record, @Param("example") ArtistsSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateByPrimaryKeySelective(Artists record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateByPrimaryKey(Artists record);
}