package sample.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import sample.model.InvoiceItems;
import sample.model.InvoiceItemsSearchCriteria;

@Mapper
public interface InvoiceItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    long countBySearchCriteria(InvoiceItemsSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int deleteBySearchCriteria(InvoiceItemsSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int deleteByPrimaryKey(Integer invoicelineid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int insert(InvoiceItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int insertSelective(InvoiceItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    List<InvoiceItems> selectBySearchCriteriaWithRowbounds(InvoiceItemsSearchCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    List<InvoiceItems> selectBySearchCriteria(InvoiceItemsSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    InvoiceItems selectByPrimaryKey(Integer invoicelineid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateBySearchCriteriaSelective(@Param("record") InvoiceItems record, @Param("example") InvoiceItemsSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateBySearchCriteria(@Param("record") InvoiceItems record, @Param("example") InvoiceItemsSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateByPrimaryKeySelective(InvoiceItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_items
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateByPrimaryKey(InvoiceItems record);
}