package sample.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import sample.model.Invoices;
import sample.model.InvoicesSearchCriteria;

@Mapper
public interface InvoicesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    long countBySearchCriteria(InvoicesSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int deleteBySearchCriteria(InvoicesSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int deleteByPrimaryKey(Integer invoiceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int insert(Invoices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int insertSelective(Invoices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    List<Invoices> selectBySearchCriteriaWithRowbounds(InvoicesSearchCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    List<Invoices> selectBySearchCriteria(InvoicesSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    Invoices selectByPrimaryKey(Integer invoiceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateBySearchCriteriaSelective(@Param("record") Invoices record, @Param("example") InvoicesSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateBySearchCriteria(@Param("record") Invoices record, @Param("example") InvoicesSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateByPrimaryKeySelective(Invoices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateByPrimaryKey(Invoices record);
}