package sample.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import sample.model.MediaTypes;
import sample.model.MediaTypesSearchCriteria;

@Mapper
public interface MediaTypesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_types
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    long countBySearchCriteria(MediaTypesSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_types
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int deleteBySearchCriteria(MediaTypesSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_types
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int deleteByPrimaryKey(Integer mediatypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_types
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int insert(MediaTypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_types
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int insertSelective(MediaTypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_types
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    List<MediaTypes> selectBySearchCriteriaWithRowbounds(MediaTypesSearchCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_types
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    List<MediaTypes> selectBySearchCriteria(MediaTypesSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_types
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    MediaTypes selectByPrimaryKey(Integer mediatypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_types
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateBySearchCriteriaSelective(@Param("record") MediaTypes record, @Param("example") MediaTypesSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_types
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateBySearchCriteria(@Param("record") MediaTypes record, @Param("example") MediaTypesSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_types
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateByPrimaryKeySelective(MediaTypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_types
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateByPrimaryKey(MediaTypes record);
}