package sample.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import sample.model.Playlists;
import sample.model.PlaylistsSearchCriteria;

@Mapper
public interface PlaylistsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    long countBySearchCriteria(PlaylistsSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int deleteBySearchCriteria(PlaylistsSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int deleteByPrimaryKey(Integer playlistid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int insert(Playlists record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int insertSelective(Playlists record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    List<Playlists> selectBySearchCriteriaWithRowbounds(PlaylistsSearchCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    List<Playlists> selectBySearchCriteria(PlaylistsSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    Playlists selectByPrimaryKey(Integer playlistid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateBySearchCriteriaSelective(@Param("record") Playlists record, @Param("example") PlaylistsSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateBySearchCriteria(@Param("record") Playlists record, @Param("example") PlaylistsSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateByPrimaryKeySelective(Playlists record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlists
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateByPrimaryKey(Playlists record);
}