package sample.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import sample.model.PlaylistTrack;
import sample.model.PlaylistTrackSearchCriteria;

@Mapper
public interface PlaylistTrackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    long countBySearchCriteria(PlaylistTrackSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int deleteBySearchCriteria(PlaylistTrackSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int deleteByPrimaryKey(@Param("playlistid") Integer playlistid, @Param("trackid") Integer trackid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int insert(PlaylistTrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int insertSelective(PlaylistTrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    List<PlaylistTrack> selectBySearchCriteriaWithRowbounds(PlaylistTrackSearchCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    List<PlaylistTrack> selectBySearchCriteria(PlaylistTrackSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateBySearchCriteriaSelective(@Param("record") PlaylistTrack record, @Param("example") PlaylistTrackSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_track
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateBySearchCriteria(@Param("record") PlaylistTrack record, @Param("example") PlaylistTrackSearchCriteria searchCriteria);
}