package sample.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import sample.model.Tracks;
import sample.model.TracksSearchCriteria;

@Mapper
public interface TracksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracks
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    long countBySearchCriteria(TracksSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracks
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int deleteBySearchCriteria(TracksSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracks
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int deleteByPrimaryKey(Integer trackid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracks
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int insert(Tracks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracks
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int insertSelective(Tracks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracks
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    List<Tracks> selectBySearchCriteriaWithRowbounds(TracksSearchCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracks
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    List<Tracks> selectBySearchCriteria(TracksSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracks
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    Tracks selectByPrimaryKey(Integer trackid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracks
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateBySearchCriteriaSelective(@Param("record") Tracks record, @Param("example") TracksSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracks
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateBySearchCriteria(@Param("record") Tracks record, @Param("example") TracksSearchCriteria searchCriteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracks
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateByPrimaryKeySelective(Tracks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracks
     *
     * @mbg.generated 2019-02-27 17:48:22
     */
    int updateByPrimaryKey(Tracks record);
}